version: '3.1'
services:
  mytest:
    build:
      context: ./
      dockerfile: DockeeFile
    image: mytest:v1.0.0
    container_name: mytest
    ports:
      - 8083:8082
    tty: true
#    command: /bin/bash